import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ActiveLink } from "@/ui/atoms/ActiveLink";
import { ProductSearch } from "@/ui/atoms/ProductSearch";
import { getCategories } from "@/api/categories";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const categories = await getCategories();

	return (
		<html lang="en">
			<body className={inter.className}>
				<header></header>
				<nav className="flex justify-around">
					<ul className="mt-2 flex justify-center space-x-4">
						<li>
							<ActiveLink href="/" exact>
								Home
							</ActiveLink>
						</li>
						<li>
							<ActiveLink href="/products">
								All
							</ActiveLink>
						</li>
						{categories.map((category) => (
							<li key={category.slug}>
								<ActiveLink href={`/categories/${category.slug}`}>{category.name}</ActiveLink>
							</li>
						))}
					</ul>
					<ProductSearch />
				</nav>
				<main className="flex min-h-screen flex-col items-center justify-between p-24">
					<section className="sm:py-18 mx-auto flex w-full max-w-2xl flex-grow flex-col px-8 py-12 sm:px-6 lg:max-w-7xl">
						{children}
					</section>
				</main>
				<footer>
					<p>@2023</p>
				</footer>
			</body>
		</html>
	);
}
